### ISSUE TITLE
any instruction for this project?

### ISSUE THREAD

**Issue by jiaminglei-lei** [Cascol-SCUT/PointClouds_Segmantic_Visualize#1]
what's the content in data? how to generate point.bin, pred.bin and ground.bin?

By the way, SCUT in your name means 'South China University of Technology' ?

**Comment by Cascol-Chen** [comment]
Thanks for the first question, I will add instruction later. 
The project is aim for **Nuscene**, but can also be extended easily by changing the function _loadPCD_ in tools/common.py, for example, you can change it as the code below to adapt to **Semantic-Kitti** Dataset
```python
def loadPCD(path):
    points = np.fromfile(path, dtype=np.float32).reshape(-1, 4)
    points = points[:, :3]
    return 
```
As is aim for **Nuscene**, _point.bin_ and _ground.bin_ is the file for point and lidarseg provided in **Nuscene**, and _pred.bin_ is what your model output for _ground.bin_ under semantic segmentation task.
You may want to know how to match _point.bin_ and the corresponding _ground.bin_, here is an example
```python
from pathlib import Path
from nuscenes import NuScenes
nusc = NuScenes(version='v1.0-trainval', dataroot='...', verbose=True)
cur_token = sample_token
ground_root = Path('root path of the ground truth lidarseg')
pred_root = Path('root path of the prediction output lidarseg')

storage = {}
for i in range(40):
    tmp = nusc.get('sample',cur_token)
    lidar_token = tmp['data']['LIDAR_TOP']
    storage[i]={
        'points': str(ground_root / nusc.get('sample_data', lidar_token)['filename']),
        'ground': str(ground_root / nusc.get('lidarseg', lidar_token)['filename']),
        'pred': str(pred_root / (lidar_token+'_lidarseg.bin'))
    }
    print(f'{i} lidar_top_file:', ground_root / nusc.get('sample_data', lidar_token)['filename'])
    print(f'{i} ground_truth_label', ground_root / nusc.get('lidarseg', lidar_token)['filename'])
    print(f'{i} pred_label', pred_root / (lidar_token+'_lidarseg.bin'))
    cur_token = tmp['next']
```

By the way, SCUT does mean for South China University of China and this project is part of my graduation project. hhh
