### ISSUE TITLE
Visualise specific scenes

### ISSUE THREAD

**Issue by Neko-coffee** [Cascol-SCUT/PointClouds_Segmantic_Visualize#2]
Greetings.
I am new to this field, how can I visualise the point cloud of a specific scene that I want. For example, I want to visualise the point cloud of scene-0001 in Nuscence.What should I do?
Looking forward to your answer.

**Comment by Cascol-Chen** [comment]
Hi,
I would suggest changing the files in the _data_ folder.
Please refer to [Issue 1](https://github.com/Cascol-Chen/PointClouds_Segmantic_Visualize/issues/1) for a more detailed guidance to collect the data.

**Comment by Neko-coffee** [comment]
> Hi, I would suggest changing the files in the _data_ folder. Please refer to [Issue 1](https://github.com/Cascol-Chen/PointClouds_Segmantic_Visualize/issues/1) for a more detailed guidance to collect the data.

Thank you very much for your reply and the guidance, I have successfully visualised the point cloud. However there is one more question, can I show the bounding box in the visualisation.

**Comment by Cascol-Chen** [comment]
Hi, it's nice to hear that you have visualized the point cloud. This project studies semantic segmentation and we do not plan to support bounding box visualization currently.
